name: testaction
on:
  commit:

jobs:
  testaction:
    name: testaction
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
