name: testaction
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  github-to-hsdes-comment:
    name: Comment on case when PR merges
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo running ls
          ls
          cd ..
          echo running ls
          ls
          echo running pwd
          pwd
          echo hello sh
          node index.js
